### ISSUE TITLE
Plugins in posthtml.config.js only work with require('posthtml-plugin')()

### ISSUE THREAD

**Issue by andreyvolokitin** [posthtml/posthtml-load-config#2]
I am trying to keep all posthtml options in posthtml.config.js. I get empty-div output from ```posthtml-loader``` (```<div></div>```) when I use following notation in ```posthtml.config.js```:
```js
module.exports = {
  plugins: {
    'posthtml-include': {},
    'posthtml-mixins': {},
  },
};
```
but everything is working fine when I use notation with ```require()```:
```js
module.exports = {
  plugins: [
    require('posthtml-include')({}),
    require('posthtml-mixins')({}),
  ],
};
```
Not sure if it is me doing something wrong, or it is a problem with ```posthtml-loader``` or ```posthtml-load-config```
### `🌐 Environment`
|OS|node|npm/yarn|package|
|:-:|:--:|:-:|:------:|
|[OS X][10.11.6]|[9.2.1]|[5.6.0]|[1.0.1]|

**Comment by Scrum** [comment]
@andreyvolokitin Hi, could you please check this after the release of the version 2.0.0 ?

**Comment by andreyvolokitin** [comment]
@Scrum Hi, will do

**Comment by Scrum** [comment]
@andreyvolokitin update posthtml-load to v2.0.1
